---@class RunBattleTemplateBattleEntry
---@field battleId integer
---@field weight integer

---@class RunBattleTemplateEntry
---@field id integer
---@field code string
---@field name string
---@field kind string
---@field expReward integer
---@field waveCountMin integer
---@field waveCountMax integer
---@field refreshTurns integer
---@field refreshOnClear boolean
---@field spawnOrder string
---@field winRule string
---@field loseRule string
---@field battleEntries RunBattleTemplateBattleEntry[]
---@field waveGroupPoolId integer
---@field bossRequired boolean|nil
---@field bossEnemyId integer|nil

---@class RunBattleTemplateModule
---@field TEMPLATES table<integer, RunBattleTemplateEntry>
---@field GetTemplate fun(templateId: integer): RunBattleTemplateEntry|nil

---@type RunBattleTemplateModule
local RunBattleTemplate = {}

---@type table<integer, RunBattleTemplateEntry>
RunBattleTemplate.TEMPLATES = {
    [201001] = {
        id = 201001,
        code = "act1_normal_early",
        name = "Act1 Normal Early",
        kind = "normal",
        -- 第一章 F1 普通：单波，避免 1 战 EXP 跨多个 partyLevel 阈值。
        expReward = 20,
        waveCountMin = 1,
        waveCountMax = 1,
        refreshTurns = 0,
        refreshOnClear = true,
        spawnOrder = "back_first_then_front",
        winRule = "reserve_empty_and_board_clear",
        loseRule = "all_hero_dead",
        battleEntries = {
            { battleId = 101001, weight = 100 },
        },
        waveGroupPoolId = 401001,
    },
    [201002] = {
        id = 201002,
        code = "act1_normal_mid",
        name = "Act1 Normal Mid",
        kind = "normal",
        -- 中期普通：从 3 波降到 2 波，缓和单战 baseXp 通胀。
        expReward = 14,
        waveCountMin = 1,
        waveCountMax = 2,
        refreshTurns = 0,
        refreshOnClear = true,
        spawnOrder = "back_first_then_front",
        winRule = "reserve_empty_and_board_clear",
        loseRule = "all_hero_dead",
        battleEntries = {
            { battleId = 101002, weight = 60 },
            { battleId = 101003, weight = 20 },
            { battleId = 101104, weight = 20 },
        },
        waveGroupPoolId = 401002,
    },
    [201003] = {
        id = 201003,
        code = "act1_normal_late",
        name = "Act1 Normal Late",
        kind = "normal",
        -- 晚期普通：从 3 波降到 2 波；保留更高 baseLevel pressure。
        expReward = 10,
        waveCountMin = 2,
        waveCountMax = 2,
        refreshTurns = 0,
        refreshOnClear = true,
        spawnOrder = "back_first_then_front",
        winRule = "reserve_empty_and_board_clear",
        loseRule = "all_hero_dead",
        battleEntries = {
            { battleId = 101003, weight = 45 },
            { battleId = 101104, weight = 55 },
        },
        waveGroupPoolId = 401003,
    },
    [201004] = {
        id = 201004,
        code = "act1_normal_f3",
        name = "Act1 Normal F3",
        kind = "normal",
        expReward = 12,
        waveCountMin = 1,
        waveCountMax = 2,
        refreshTurns = 0,
        refreshOnClear = true,
        spawnOrder = "back_first_then_front",
        winRule = "reserve_empty_and_board_clear",
        loseRule = "all_hero_dead",
        battleEntries = {
            { battleId = 101004, weight = 100 },
        },
        waveGroupPoolId = 401004,
    },
    [201101] = {
        id = 201101,
        code = "act1_elite_mid",
        name = "Act1 Elite Mid",
        kind = "elite",
        expReward = 16,
        -- 阶段 1 修复：早期 elite 在 economy-heavy 路线（F3/F4 跳过战斗）时玩家
        -- 仅 partyLevel≈4，多波累积 ≥8 个怪足以 wipe。统一为单波 4 怪：仍保持
        -- 高 CR 怪物的精英压强，但不会因数量碾压低战力路线。
        waveCountMin = 1,
        waveCountMax = 1,
        refreshTurns = 0,
        refreshOnClear = true,
        spawnOrder = "back_first_then_front",
        winRule = "reserve_empty_and_board_clear",
        loseRule = "all_hero_dead",
        battleEntries = {
            { battleId = 101101, weight = 55 },
            { battleId = 101102, weight = 45 },
        },
        waveGroupPoolId = 401101,
    },
    [201102] = {
        id = 201102,
        code = "act1_elite_late",
        name = "Act1 Elite Late",
        kind = "elite",
        expReward = 12,
        -- 阶段 1 修复：与 201101 同因，将 wave 数下调到 1，避免 economy-heavy 路线
        -- 在 F5 第一个 elite 必然 wipe；保留更高 baseLevel/pressure 以体现"late"。
        waveCountMin = 1,
        waveCountMax = 1,
        refreshTurns = 0,
        refreshOnClear = true,
        spawnOrder = "back_first_then_front",
        winRule = "reserve_empty_and_board_clear",
        loseRule = "all_hero_dead",
        battleEntries = {
            { battleId = 101101, weight = 35 },
            { battleId = 101102, weight = 65 },
        },
        waveGroupPoolId = 401102,
    },
    [201201] = {
        id = 201201,
        code = "act1_boss",
        name = "Act1 Boss",
        kind = "boss",
        expReward = 14,
        waveCountMin = 2,
        waveCountMax = 2,
        refreshTurns = 0,
        refreshOnClear = true,
        spawnOrder = "back_first_then_front",
        winRule = "reserve_empty_and_board_clear",
        loseRule = "all_hero_dead",
        battleEntries = {
            { battleId = 101201, weight = 100 },
        },
        waveGroupPoolId = 401201,
        bossRequired = true,
        bossEnemyId = 910006,
    },
    [201301] = {
        id = 201301,
        code = "act1_event_battle_skirmish",
        name = "Act1 Event Battle Skirmish",
        kind = "event_battle",
        expReward = 12,
        waveCountMin = 1,
        waveCountMax = 1,
        refreshTurns = 0,
        refreshOnClear = true,
        spawnOrder = "back_first_then_front",
        winRule = "reserve_empty_and_board_clear",
        loseRule = "all_hero_dead",
        battleEntries = {
            { battleId = 101001, weight = 100 },
        },
        waveGroupPoolId = 401001,
    },
    [201302] = {
        id = 201302,
        code = "act1_event_battle_ritual",
        name = "Act1 Event Battle Ritual",
        kind = "event_battle",
        expReward = 10,
        waveCountMin = 1,
        waveCountMax = 2,
        refreshTurns = 0,
        refreshOnClear = true,
        spawnOrder = "back_first_then_front",
        winRule = "reserve_empty_and_board_clear",
        loseRule = "all_hero_dead",
        battleEntries = {
            { battleId = 101002, weight = 50 },
            { battleId = 101003, weight = 20 },
            { battleId = 101104, weight = 30 },
        },
        waveGroupPoolId = 401002,
    },
    [202001] = {
        id = 202001,
        code = "act2_normal_early",
        name = "Act2 Normal Early",
        kind = "normal",
        expReward = 26,
        waveCountMin = 1,
        waveCountMax = 1,
        refreshTurns = 0,
        refreshOnClear = true,
        spawnOrder = "back_first_then_front",
        winRule = "reserve_empty_and_board_clear",
        loseRule = "all_hero_dead",
        battleEntries = {
            { battleId = 102001, weight = 100 },
        },
        waveGroupPoolId = 402001,
    },
    [202002] = {
        id = 202002,
        code = "act2_normal_mid",
        name = "Act2 Normal Mid",
        kind = "normal",
        expReward = 20,
        waveCountMin = 1,
        waveCountMax = 1,
        refreshTurns = 0,
        refreshOnClear = true,
        spawnOrder = "back_first_then_front",
        winRule = "reserve_empty_and_board_clear",
        loseRule = "all_hero_dead",
        battleEntries = {
            { battleId = 102002, weight = 65 },
            { battleId = 102003, weight = 35 },
        },
        waveGroupPoolId = 402002,
    },
    [202003] = {
        id = 202003,
        code = "act2_normal_late",
        name = "Act2 Normal Late",
        kind = "normal",
        expReward = 16,
        waveCountMin = 2,
        waveCountMax = 2,
        refreshTurns = 0,
        refreshOnClear = true,
        spawnOrder = "back_first_then_front",
        winRule = "reserve_empty_and_board_clear",
        loseRule = "all_hero_dead",
        battleEntries = {
            { battleId = 102003, weight = 45 },
            { battleId = 102004, weight = 55 },
        },
        waveGroupPoolId = 402003,
    },
    [202101] = {
        id = 202101,
        code = "act2_elite_mid",
        name = "Act2 Elite Mid",
        kind = "elite",
        expReward = 22,
        waveCountMin = 1,
        waveCountMax = 1,
        refreshTurns = 0,
        refreshOnClear = true,
        spawnOrder = "back_first_then_front",
        winRule = "reserve_empty_and_board_clear",
        loseRule = "all_hero_dead",
        battleEntries = {
            { battleId = 102101, weight = 55 },
            { battleId = 102102, weight = 45 },
        },
        waveGroupPoolId = 402101,
    },
    [202102] = {
        id = 202102,
        code = "act2_elite_late",
        name = "Act2 Elite Late",
        kind = "elite",
        expReward = 18,
        waveCountMin = 1,
        waveCountMax = 1,
        refreshTurns = 0,
        refreshOnClear = true,
        spawnOrder = "back_first_then_front",
        winRule = "reserve_empty_and_board_clear",
        loseRule = "all_hero_dead",
        battleEntries = {
            { battleId = 102101, weight = 25 },
            { battleId = 102102, weight = 75 },
        },
        waveGroupPoolId = 402102,
    },
    [202201] = {
        id = 202201,
        code = "act2_boss",
        name = "Act2 Boss",
        kind = "boss",
        expReward = 22,
        waveCountMin = 2,
        waveCountMax = 2,
        refreshTurns = 0,
        refreshOnClear = true,
        spawnOrder = "back_first_then_front",
        winRule = "reserve_empty_and_board_clear",
        loseRule = "all_hero_dead",
        battleEntries = {
            { battleId = 102201, weight = 100 },
        },
        waveGroupPoolId = 402201,
        bossRequired = true,
        bossEnemyId = 910006,
    },
    [203001] = {
        id = 203001,
        code = "act3_normal_early",
        name = "Act3 Normal Early",
        kind = "normal",
        expReward = 30,
        waveCountMin = 1,
        waveCountMax = 1,
        refreshTurns = 0,
        refreshOnClear = true,
        spawnOrder = "back_first_then_front",
        winRule = "reserve_empty_and_board_clear",
        loseRule = "all_hero_dead",
        battleEntries = {
            { battleId = 103001, weight = 100 },
        },
        waveGroupPoolId = 403001,
    },
    [203002] = {
        id = 203002,
        code = "act3_normal_mid",
        name = "Act3 Normal Mid",
        kind = "normal",
        expReward = 24,
        waveCountMin = 1,
        waveCountMax = 2,
        refreshTurns = 0,
        refreshOnClear = true,
        spawnOrder = "back_first_then_front",
        winRule = "reserve_empty_and_board_clear",
        loseRule = "all_hero_dead",
        battleEntries = {
            { battleId = 103002, weight = 60 },
            { battleId = 103003, weight = 40 },
        },
        waveGroupPoolId = 403002,
    },
    [203003] = {
        id = 203003,
        code = "act3_normal_late",
        name = "Act3 Normal Late",
        kind = "normal",
        expReward = 20,
        waveCountMin = 2,
        waveCountMax = 2,
        refreshTurns = 0,
        refreshOnClear = true,
        spawnOrder = "back_first_then_front",
        winRule = "reserve_empty_and_board_clear",
        loseRule = "all_hero_dead",
        battleEntries = {
            { battleId = 103003, weight = 40 },
            { battleId = 103004, weight = 60 },
        },
        waveGroupPoolId = 403003,
    },
    [203101] = {
        id = 203101,
        code = "act3_elite_mid",
        name = "Act3 Elite Mid",
        kind = "elite",
        expReward = 26,
        waveCountMin = 1,
        waveCountMax = 1,
        refreshTurns = 0,
        refreshOnClear = true,
        spawnOrder = "back_first_then_front",
        winRule = "reserve_empty_and_board_clear",
        loseRule = "all_hero_dead",
        battleEntries = {
            { battleId = 103101, weight = 45 },
            { battleId = 103102, weight = 55 },
        },
        waveGroupPoolId = 403101,
    },
    [203102] = {
        id = 203102,
        code = "act3_elite_late",
        name = "Act3 Elite Late",
        kind = "elite",
        expReward = 22,
        waveCountMin = 1,
        waveCountMax = 1,
        refreshTurns = 0,
        refreshOnClear = true,
        spawnOrder = "back_first_then_front",
        winRule = "reserve_empty_and_board_clear",
        loseRule = "all_hero_dead",
        battleEntries = {
            { battleId = 103101, weight = 20 },
            { battleId = 103102, weight = 80 },
        },
        waveGroupPoolId = 403102,
    },
    [203201] = {
        id = 203201,
        code = "act3_boss",
        name = "Act3 Boss",
        kind = "boss",
        expReward = 28,
        waveCountMin = 2,
        waveCountMax = 2,
        refreshTurns = 0,
        refreshOnClear = true,
        spawnOrder = "back_first_then_front",
        winRule = "reserve_empty_and_board_clear",
        loseRule = "all_hero_dead",
        battleEntries = {
            { battleId = 103201, weight = 100 },
        },
        waveGroupPoolId = 403201,
        bossRequired = true,
        bossEnemyId = 910007,
    },
}

function RunBattleTemplate.GetTemplate(templateId)
    return RunBattleTemplate.TEMPLATES[templateId]
end

return RunBattleTemplate
