local RunCardRewardPool = {}

RunCardRewardPool.CARDS = {
    {
        id = 101,
        skillId = 80001011,
        classId = 1,
        ownerPolicy = "class",
        rarity = "common",
        weight = 12,
        cost = 1,
        name = "潜袭短击",
        description = "加入 1 张游荡者基础攻击牌。稳定打击单个敌人。",
    },
    {
        id = 102,
        skillId = 80001013,
        classId = 1,
        ownerPolicy = "class",
        rarity = "uncommon",
        weight = 8,
        cost = 1,
        name = "诡诈打击",
        description = "加入 1 张游荡者技巧牌。以诡诈攻势压低目标血线。",
    },
    {
        id = 103,
        skillId = 80002001,
        classId = 2,
        ownerPolicy = "class",
        rarity = "common",
        weight = 12,
        cost = 1,
        name = "战士挥砍",
        description = "加入 1 张战士基础攻击牌。稳定造成武器伤害。",
    },
    {
        id = 104,
        skillId = 80002005,
        classId = 2,
        ownerPolicy = "class",
        rarity = "uncommon",
        weight = 8,
        cost = 1,
        name = "护卫架势",
        description = "加入 1 张战士护卫牌。转入防护姿态，稳住前排。",
    },
    {
        id = 105,
        skillId = 80002006,
        classId = 2,
        ownerPolicy = "class",
        rarity = "common",
        weight = 12,
        cost = 1,
        name = "战术回气",
        description = "加入 1 张战士回气牌。回复自身生命，保持战线。",
    },
    {
        id = 106,
        skillId = 80003011,
        classId = 3,
        ownerPolicy = "class",
        rarity = "common",
        weight = 12,
        cost = 1,
        name = "徒手打击",
        description = "加入 1 张武僧基础攻击牌。快速打击单个敌人。",
    },
    {
        id = 107,
        skillId = 80003013,
        classId = 3,
        ownerPolicy = "class",
        rarity = "uncommon",
        weight = 8,
        cost = 1,
        name = "震慑拳",
        description = "加入 1 张武僧控制牌。尝试打断敌方节奏。",
    },
    {
        id = 108,
        skillId = 80003014,
        classId = 3,
        ownerPolicy = "class",
        rarity = "rare",
        weight = 6,
        cost = 2,
        name = "影步连打",
        description = "加入 1 张武僧连击牌。以高频打击压制目标。",
    },
    {
        id = 109,
        skillId = 80003015,
        classId = 3,
        ownerPolicy = "class",
        rarity = "uncommon",
        weight = 8,
        cost = 1,
        name = "明镜止水",
        description = "加入 1 张武僧调息牌。恢复状态并延长战线。",
    },
    {
        id = 110,
        skillId = 80004011,
        classId = 4,
        ownerPolicy = "class",
        rarity = "common",
        weight = 12,
        cost = 1,
        name = "圣武打击",
        description = "加入 1 张圣武士基础攻击牌。以圣武之力攻击敌人。",
    },
    {
        id = 111,
        skillId = 80004013,
        classId = 4,
        ownerPolicy = "class",
        rarity = "uncommon",
        weight = 8,
        cost = 1,
        name = "圣疗",
        description = "加入 1 张圣武士治疗牌。救助受伤友军。",
    },
    {
        id = 112,
        skillId = 80004014,
        classId = 4,
        ownerPolicy = "class",
        rarity = "rare",
        weight = 6,
        cost = 2,
        name = "破邪斩",
        description = "加入 1 张圣武士爆发牌。对邪恶敌人施以重击。",
    },
    {
        id = 113,
        skillId = 80004015,
        classId = 4,
        ownerPolicy = "class",
        rarity = "uncommon",
        weight = 8,
        cost = 1,
        name = "神圣灵光",
        description = "加入 1 张圣武士灵光牌。强化队伍防护窗口。",
    },
    {
        id = 114,
        skillId = 80005011,
        classId = 5,
        ownerPolicy = "class",
        rarity = "common",
        weight = 12,
        cost = 1,
        name = "远程射击",
        description = "加入 1 张游侠基础攻击牌。远程打击单个敌人。",
    },
    {
        id = 115,
        skillId = 80005013,
        classId = 5,
        ownerPolicy = "class",
        rarity = "common",
        weight = 12,
        cost = 1,
        name = "二连射",
        description = "加入 1 张游侠二连射牌。对最多 2 名敌人射击。",
    },
    {
        id = 116,
        skillId = 80005014,
        classId = 5,
        ownerPolicy = "class",
        rarity = "uncommon",
        weight = 8,
        cost = 1,
        name = "暮影射击",
        description = "加入 1 张游侠精准牌。集中火力打击关键目标。",
    },
    {
        id = 117,
        skillId = 80005015,
        classId = 5,
        ownerPolicy = "class",
        rarity = "uncommon",
        weight = 8,
        cost = 1,
        name = "缠绕箭",
        description = "加入 1 张游侠控制牌。限制敌方行动。",
    },
    {
        id = 118,
        skillId = 80005109,
        classId = 5,
        ownerPolicy = "class",
        rarity = "rare",
        weight = 6,
        cost = 2,
        name = "箭雨",
        description = "加入 1 张游侠范围牌。覆盖敌方阵列。",
    },
    {
        id = 119,
        skillId = 80006011,
        classId = 6,
        ownerPolicy = "class",
        rarity = "common",
        weight = 12,
        cost = 1,
        name = "圣火术",
        description = "加入 1 张牧师基础法术牌。以圣焰灼烧敌人。",
    },
    {
        id = 120,
        skillId = 80006012,
        classId = 6,
        ownerPolicy = "class",
        rarity = "common",
        weight = 12,
        cost = 1,
        name = "治愈真言",
        description = "加入 1 张牧师治疗牌。治疗生命最低友军。",
    },
    {
        id = 121,
        skillId = 80006015,
        classId = 6,
        ownerPolicy = "class",
        rarity = "uncommon",
        weight = 8,
        cost = 1,
        name = "祝福术",
        description = "加入 1 张牧师增益牌。提高队伍稳定性。",
    },
    {
        id = 122,
        skillId = 80006016,
        classId = 6,
        ownerPolicy = "class",
        rarity = "rare",
        weight = 6,
        cost = 2,
        name = "驱散亡灵",
        description = "加入 1 张牧师光耀牌。对敌方多目标造成伤害并减速。",
    },
    {
        id = 123,
        skillId = 80007001,
        classId = 7,
        ownerPolicy = "class",
        rarity = "common",
        weight = 12,
        cost = 1,
        name = "火焰弹",
        description = "加入 1 张火焰法师基础法术牌。点燃单个敌人。",
    },
    {
        id = 124,
        skillId = 80007003,
        classId = 7,
        ownerPolicy = "class",
        rarity = "common",
        weight = 10,
        cost = 1,
        name = "灰烬爆燃",
        description = "加入 1 张术士火焰牌。打击目标并刷新燃烧。",
    },
    {
        id = 125,
        skillId = 80007004,
        classId = 7,
        ownerPolicy = "class",
        rarity = "rare",
        weight = 6,
        cost = 2,
        name = "烈焰风暴",
        description = "加入 1 张火焰法师范围牌。以烈焰压制敌群。",
    },
    {
        id = 126,
        skillId = 80008001,
        classId = 8,
        ownerPolicy = "class",
        rarity = "common",
        weight = 12,
        cost = 1,
        name = "寒霜射线",
        description = "加入 1 张冰霜法师基础法术牌。以寒霜打击敌人。",
    },
    {
        id = 127,
        skillId = 80008003,
        classId = 8,
        ownerPolicy = "class",
        rarity = "rare",
        weight = 6,
        cost = 2,
        name = "冻结新星",
        description = "加入 1 张法师控制牌。造成冰霜伤害并尝试冻结。",
    },
    {
        id = 128,
        skillId = 80008004,
        classId = 8,
        ownerPolicy = "class",
        rarity = "rare",
        weight = 6,
        cost = 2,
        name = "暴风雪",
        description = "加入 1 张冰霜法师范围牌。压制敌方阵列。",
    },
    {
        id = 129,
        skillId = 80009001,
        classId = 9,
        ownerPolicy = "class",
        rarity = "common",
        weight = 12,
        cost = 1,
        name = "邪能冲击",
        description = "加入 1 张魔契师基础法术牌。以邪能打击敌人。",
    },
    {
        id = 130,
        skillId = 80009003,
        classId = 9,
        ownerPolicy = "class",
        rarity = "rare",
        weight = 6,
        cost = 2,
        name = "雷链",
        description = "加入 1 张魔契师雷电牌。当前目标与额外敌人连锁受击。",
    },
    {
        id = 131,
        skillId = 80009004,
        classId = 9,
        ownerPolicy = "class",
        rarity = "rare",
        weight = 6,
        cost = 2,
        name = "雷暴",
        description = "加入 1 张魔契师范围牌。以雷暴压制敌群。",
    },
    {
        id = 132,
        skillId = 80010011,
        classId = 10,
        ownerPolicy = "class",
        rarity = "common",
        weight = 12,
        cost = 1,
        name = "狂斧劈砍",
        description = "加入 1 张狂战士基础攻击牌。以重斧打击敌人。",
    },
    {
        id = 133,
        skillId = 80010013,
        classId = 10,
        ownerPolicy = "class",
        rarity = "uncommon",
        weight = 8,
        cost = 1,
        name = "重击",
        description = "加入 1 张狂战士压制牌。集中力量重创目标。",
    },
}

function RunCardRewardPool.GetCard(cardId)
    local id = tonumber(cardId)
    for _, entry in ipairs(RunCardRewardPool.CARDS) do
        if tonumber(entry.id) == id then
            return entry
        end
    end
    return nil
end

function RunCardRewardPool.GetAllCards()
    return RunCardRewardPool.CARDS
end

return RunCardRewardPool
