local RunCardRewardPool = {}

RunCardRewardPool.CARDS = {
    {
        id = 101,
        skillId = 80001011,
        classId = 1,
        ownerPolicy = "class",
        rarity = "common",
        weight = 12,
        cost = 1,
        name = "潜袭短击",
        description = "加入 1 张游荡者循环攻击牌。打击单个敌人，抽 1 张牌并获得 1 蓄势。",
        cardEffects = { drawCards = 1, momentumGain = 1 },
    },
    {
        id = 102,
        skillId = 80001013,
        classId = 1,
        ownerPolicy = "class",
        rarity = "uncommon",
        weight = 8,
        cost = 1,
        name = "诡诈打击",
        description = "加入 1 张游荡者节奏牌。若耗 1 蓄势，本张降 1 费并返还 1 点能量，本场消耗。",
        cardEffects = { momentumSpend = 1, momentumCostReduction = 1, momentumEnergyGain = 1, exhaust = true },
    },
    {
        id = 103,
        skillId = 80002001,
        classId = 2,
        ownerPolicy = "class",
        rarity = "common",
        weight = 12,
        cost = 1,
        name = "战士挥砍",
        description = "加入 1 张战士攻防牌。稳定造成武器伤害，获得 3 Guard 与 1 蓄势。",
        cardEffects = { guardValue = 3, momentumGain = 1 },
    },
    {
        id = 104,
        skillId = 80002005,
        classId = 2,
        ownerPolicy = "class",
        rarity = "uncommon",
        weight = 8,
        cost = 1,
        name = "护卫架势",
        description = "加入 1 张战士保留防御牌。获得额外 8 Guard 与 1 蓄势，回合结束保留。",
        cardEffects = { guardValue = 8, momentumGain = 1, retain = true },
    },
    {
        id = 105,
        skillId = 80002006,
        classId = 2,
        ownerPolicy = "class",
        rarity = "common",
        weight = 12,
        cost = 1,
        name = "战术回气",
        description = "加入 1 张战士回气窗口牌。若耗 1 蓄势，本张降 1 费并获得 4 Guard。",
        cardEffects = { momentumSpend = 1, momentumCostReduction = 1, momentumGuardValue = 4 },
    },
    {
        id = 106,
        skillId = 80003011,
        classId = 3,
        ownerPolicy = "class",
        rarity = "common",
        weight = 12,
        cost = 1,
        name = "徒手打击",
        description = "加入 1 张武僧连段牌。快速打击单个敌人，返还 1 点能量并获得 1 蓄势。",
        cardEffects = { energyGain = 1, momentumGain = 1 },
    },
    {
        id = 107,
        skillId = 80003013,
        classId = 3,
        ownerPolicy = "class",
        rarity = "uncommon",
        weight = 8,
        cost = 1,
        name = "震慑拳",
        description = "加入 1 张武僧控制循环牌。尝试打断敌方节奏，抽 1 张牌并获得 1 蓄势。",
        cardEffects = { drawCards = 1, momentumGain = 1 },
    },
    {
        id = 108,
        skillId = 80003014,
        classId = 3,
        ownerPolicy = "class",
        rarity = "rare",
        weight = 6,
        cost = 2,
        name = "影步连打",
        description = "加入 1 张武僧爆发牌。若耗 1 蓄势，本张降 1 费、返还 1 点能量并抽 1 张牌，本场消耗。",
        cardEffects = { momentumSpend = 1, momentumCostReduction = 1, momentumEnergyGain = 1, momentumDrawCards = 1, exhaust = true },
    },
    {
        id = 109,
        skillId = 80003015,
        classId = 3,
        ownerPolicy = "class",
        rarity = "uncommon",
        weight = 8,
        cost = 1,
        name = "明镜止水",
        description = "加入 1 张武僧调息牌。恢复状态，获得 6 Guard 与 1 蓄势，回合结束保留。",
        cardEffects = { guardValue = 6, momentumGain = 1, retain = true },
    },
    {
        id = 110,
        skillId = 80004011,
        classId = 4,
        ownerPolicy = "class",
        rarity = "common",
        weight = 12,
        cost = 1,
        name = "圣武打击",
        description = "加入 1 张圣武士攻防牌。以圣武之力攻击敌人，获得 3 Guard 与 1 蓄势。",
        cardEffects = { guardValue = 3, momentumGain = 1 },
    },
    {
        id = 111,
        skillId = 80004013,
        classId = 4,
        ownerPolicy = "class",
        rarity = "uncommon",
        weight = 8,
        cost = 1,
        name = "圣疗",
        description = "加入 1 张圣武士保留治疗牌。若耗 1 蓄势，本张降 1 费并获得 4 Guard，本场消耗。",
        cardEffects = { momentumSpend = 1, momentumCostReduction = 1, momentumGuardValue = 4, retain = true, exhaust = true },
    },
    {
        id = 112,
        skillId = 80004014,
        classId = 4,
        ownerPolicy = "class",
        rarity = "rare",
        weight = 6,
        cost = 2,
        name = "破邪斩",
        description = "加入 1 张圣武士爆发牌。若耗 1 蓄势，本张降 1 费并返还 1 点能量，本场消耗。",
        cardEffects = { momentumSpend = 1, momentumCostReduction = 1, momentumEnergyGain = 1, exhaust = true },
    },
    {
        id = 113,
        skillId = 80004015,
        classId = 4,
        ownerPolicy = "class",
        rarity = "uncommon",
        weight = 8,
        cost = 1,
        name = "神圣灵光",
        description = "加入 1 张圣武士灵光牌。强化队伍防护窗口，获得 1 蓄势，回合结束保留。",
        cardEffects = { momentumGain = 1, retain = true },
    },
    {
        id = 114,
        skillId = 80005011,
        classId = 5,
        ownerPolicy = "class",
        rarity = "common",
        weight = 12,
        cost = 1,
        name = "远程射击",
        description = "加入 1 张游侠循环攻击牌。远程打击单个敌人，抽 1 张牌并获得 1 蓄势。",
        cardEffects = { drawCards = 1, momentumGain = 1 },
    },
    {
        id = 115,
        skillId = 80005013,
        classId = 5,
        ownerPolicy = "class",
        rarity = "common",
        weight = 12,
        cost = 1,
        name = "二连射",
        description = "加入 1 张游侠二连射牌。对最多 2 名敌人射击，抽 1 张牌并获得 1 蓄势。",
        cardEffects = { drawCards = 1, momentumGain = 1 },
    },
    {
        id = 116,
        skillId = 80005014,
        classId = 5,
        ownerPolicy = "class",
        rarity = "uncommon",
        weight = 8,
        cost = 1,
        name = "暮影射击",
        description = "加入 1 张游侠精准牌。若耗 1 蓄势，本张降 1 费并返还 1 点能量。",
        cardEffects = { momentumSpend = 1, momentumCostReduction = 1, momentumEnergyGain = 1 },
    },
    {
        id = 117,
        skillId = 80005015,
        classId = 5,
        ownerPolicy = "class",
        rarity = "uncommon",
        weight = 8,
        cost = 1,
        name = "缠绕箭",
        description = "加入 1 张游侠保留控制牌。限制敌方行动，获得 1 蓄势，回合结束保留。",
        cardEffects = { momentumGain = 1, retain = true },
    },
    {
        id = 118,
        skillId = 80005109,
        classId = 5,
        ownerPolicy = "class",
        rarity = "rare",
        weight = 6,
        cost = 2,
        name = "箭雨",
        description = "加入 1 张游侠范围爆发牌。若耗 1 蓄势，本张降 1 费并抽 1 张牌，本场消耗。",
        cardEffects = { momentumSpend = 1, momentumCostReduction = 1, momentumDrawCards = 1, exhaust = true },
    },
    {
        id = 119,
        skillId = 80006011,
        classId = 6,
        ownerPolicy = "class",
        rarity = "common",
        weight = 12,
        cost = 1,
        name = "圣火术",
        description = "加入 1 张牧师循环法术牌。以圣焰灼烧敌人，抽 1 张牌并获得 1 蓄势。",
        cardEffects = { drawCards = 1, momentumGain = 1 },
    },
    {
        id = 120,
        skillId = 80006012,
        classId = 6,
        ownerPolicy = "class",
        rarity = "common",
        weight = 12,
        cost = 1,
        name = "治愈真言",
        description = "加入 1 张牧师保留治疗牌。治疗生命最低友军，获得 1 蓄势，回合结束保留。",
        cardEffects = { momentumGain = 1, retain = true },
    },
    {
        id = 121,
        skillId = 80006015,
        classId = 6,
        ownerPolicy = "class",
        rarity = "uncommon",
        weight = 8,
        cost = 1,
        name = "祝福术",
        description = "加入 1 张牧师增益牌。提高队伍稳定性，抽 1 张牌并获得 1 蓄势。",
        cardEffects = { drawCards = 1, momentumGain = 1 },
    },
    {
        id = 122,
        skillId = 80006016,
        classId = 6,
        ownerPolicy = "class",
        rarity = "rare",
        weight = 6,
        cost = 2,
        name = "驱散亡灵",
        description = "加入 1 张牧师光耀爆发牌。若耗 1 蓄势，本张降 1 费并抽 1 张牌，本场消耗。",
        cardEffects = { momentumSpend = 1, momentumCostReduction = 1, momentumDrawCards = 1, exhaust = true },
    },
    {
        id = 123,
        skillId = 80007001,
        classId = 7,
        ownerPolicy = "class",
        rarity = "common",
        weight = 12,
        cost = 1,
        name = "火焰弹",
        description = "加入 1 张火焰法师循环法术牌。点燃单个敌人，抽 1 张牌并获得 1 蓄势。",
        cardEffects = { drawCards = 1, momentumGain = 1 },
    },
    {
        id = 124,
        skillId = 80007003,
        classId = 7,
        ownerPolicy = "class",
        rarity = "common",
        weight = 10,
        cost = 1,
        name = "灰烬爆燃",
        description = "加入 1 张火焰法师回能牌。若耗 1 蓄势，本张降 1 费并返还 1 点能量。",
        cardEffects = { momentumSpend = 1, momentumCostReduction = 1, momentumEnergyGain = 1 },
    },
    {
        id = 125,
        skillId = 80007004,
        classId = 7,
        ownerPolicy = "class",
        rarity = "rare",
        weight = 6,
        cost = 2,
        name = "烈焰风暴",
        description = "加入 1 张火焰法师范围爆发牌。若耗 1 蓄势，本张降 1 费并返还 1 点能量，本场消耗。",
        cardEffects = { momentumSpend = 1, momentumCostReduction = 1, momentumEnergyGain = 1, exhaust = true },
    },
    {
        id = 126,
        skillId = 80008001,
        classId = 8,
        ownerPolicy = "class",
        rarity = "common",
        weight = 12,
        cost = 1,
        name = "寒霜射线",
        description = "加入 1 张冰霜法师循环法术牌。以寒霜打击敌人，抽 1 张牌并获得 1 蓄势。",
        cardEffects = { drawCards = 1, momentumGain = 1 },
    },
    {
        id = 127,
        skillId = 80008003,
        classId = 8,
        ownerPolicy = "class",
        rarity = "rare",
        weight = 6,
        cost = 2,
        name = "冻结新星",
        description = "加入 1 张冰霜法师保留控制牌。若耗 1 蓄势，本张降 1 费并抽 1 张牌，回合结束保留。",
        cardEffects = { momentumSpend = 1, momentumCostReduction = 1, momentumDrawCards = 1, retain = true },
    },
    {
        id = 128,
        skillId = 80008004,
        classId = 8,
        ownerPolicy = "class",
        rarity = "rare",
        weight = 6,
        cost = 2,
        name = "暴风雪",
        description = "加入 1 张冰霜法师范围爆发牌。若耗 1 蓄势，本张降 1 费并抽 1 张牌，本场消耗。",
        cardEffects = { momentumSpend = 1, momentumCostReduction = 1, momentumDrawCards = 1, exhaust = true },
    },
    {
        id = 129,
        skillId = 80009001,
        classId = 9,
        ownerPolicy = "class",
        rarity = "common",
        weight = 12,
        cost = 1,
        name = "邪能冲击",
        description = "加入 1 张魔契师循环法术牌。以邪能打击敌人，抽 1 张牌并获得 1 蓄势。",
        cardEffects = { drawCards = 1, momentumGain = 1 },
    },
    {
        id = 130,
        skillId = 80009003,
        classId = 9,
        ownerPolicy = "class",
        rarity = "rare",
        weight = 6,
        cost = 2,
        name = "雷链",
        description = "加入 1 张魔契师雷电节奏牌。若耗 1 蓄势，本张降 1 费并返还 1 点能量。",
        cardEffects = { momentumSpend = 1, momentumCostReduction = 1, momentumEnergyGain = 1 },
    },
    {
        id = 131,
        skillId = 80009004,
        classId = 9,
        ownerPolicy = "class",
        rarity = "rare",
        weight = 6,
        cost = 2,
        name = "雷暴",
        description = "加入 1 张魔契师范围爆发牌。若耗 1 蓄势，本张降 1 费、返还 1 能量并抽 1 张牌，本场消耗。",
        cardEffects = { momentumSpend = 1, momentumCostReduction = 1, momentumEnergyGain = 1, momentumDrawCards = 1, exhaust = true },
    },
    {
        id = 132,
        skillId = 80010011,
        classId = 10,
        ownerPolicy = "class",
        rarity = "common",
        weight = 12,
        cost = 1,
        name = "狂斧劈砍",
        description = "加入 1 张狂战士攻防牌。以重斧打击敌人，获得 4 Guard 与 1 蓄势。",
        cardEffects = { guardValue = 4, momentumGain = 1 },
    },
    {
        id = 133,
        skillId = 80010013,
        classId = 10,
        ownerPolicy = "class",
        rarity = "uncommon",
        weight = 8,
        cost = 1,
        name = "重击",
        description = "加入 1 张狂战士压制牌。若耗 1 蓄势，本张降 1 费并获得 4 Guard，本场消耗。",
        cardEffects = { momentumSpend = 1, momentumCostReduction = 1, momentumGuardValue = 4, exhaust = true },
    },
}

function RunCardRewardPool.GetCard(cardId)
    local id = tonumber(cardId)
    for _, entry in ipairs(RunCardRewardPool.CARDS) do
        if tonumber(entry.id) == id then
            return entry
        end
    end
    return nil
end

function RunCardRewardPool.GetAllCards()
    return RunCardRewardPool.CARDS
end

return RunCardRewardPool
