---@class RuntimeSkillEntry
---@field id integer
---@field symbol string
---@field runtimeKind "active"|"passive"
---@field designKind "active"|"passive"|"reaction"|"feature"
---@field classId integer
---@field name string
---@field hidden boolean
---@field cooldown integer
---@field luaFile string|nil
---@field trigger string|nil
---@field execution table|nil
---@field tags string[]
---@field runtimeData table|nil

local SkillRuntimeConfig = {}

SkillRuntimeConfig.Ids = {
    rogue_basic_attack = 80001011,
    rogue_execute_strike = 80001013,
    rogue_trickster_blade = 80001014,
    rogue_swashbuckler_thrust = 80001015,
    rogue_sneak_attack = 80001101,
    rogue_shadow_step = 80001102,
    rogue_flanking_expert = 80001103,
    rogue_evasive_tumble = 80001104,
    rogue_sneak_attack_mastery = 80001105,
    rogue_subclass_mastery = 80001106,
    rogue_lightfoot_mastery = 80001107,
    rogue_uncanny_dodge = 80001108,
    rogue_executioner = 80001109,
    rogue_shadow_dancer = 80001110,
    rogue_survivor = 80001111,
    fighter_basic_attack = 80002001,
    fighter_action_surge = 80002003,
    fighter_guard_stance = 80002005,
    fighter_second_wind = 80002101,
    fighter_precise_attack = 80002102,
    fighter_counter_basic = 80002104,
    fighter_guard_counter = 80002105,
    fighter_second_wind_mastery = 80002107,
    fighter_extra_attack = 80002109,
    fighter_sweeping_attack = 80002110,
    monk_basic_attack = 80003011,
    monk_open_hand = 80003013,
    monk_shadow_combo = 80003014,
    monk_harmonize = 80003015,
    monk_martial_arts = 80003101,
    monk_flurry_training = 80003102,
    monk_iron_mind = 80003103,
    monk_swift_step = 80003104,
    monk_body_mastery = 80003105,
    monk_combo_mastery = 80003106,
    monk_body_guard = 80003107,
    monk_extra_attack = 80003108,
    monk_disruption_mastery = 80003109,
    monk_purity_mastery = 80003110,
    paladin_basic_attack = 80004011,
    paladin_lay_on_hands = 80004013,
    paladin_vengeance_smite = 80004014,
    paladin_guardian_aura = 80004015,
    paladin_divine_smite = 80004101,
    paladin_shelter_prayer = 80004102,
    paladin_heavy_armor_prayer = 80004103,
    paladin_judgement_prayer = 80004104,
    paladin_smite_mastery = 80004105,
    paladin_healing_mastery = 80004106,
    paladin_aura_mastery = 80004107,
    paladin_extra_attack = 80004108,
    paladin_execution_knight = 80004109,
    paladin_merciful_knight = 80004110,
    paladin_sanctuary_knight = 80004111,
    ranger_basic_attack = 80005011,
    ranger_hunter_shot = 80005013,
    ranger_shadow_shot = 80005014,
    ranger_snare_shot = 80005015,
    ranger_hunter_mark = 80005101,
    ranger_tracking_skill = 80005102,
    ranger_precise_shot = 80005103,
    ranger_wild_endurance = 80005104,
    ranger_mark_mastery = 80005105,
    ranger_subclass_mastery = 80005106,
    ranger_survival_mastery = 80005107,
    ranger_extra_attack = 80005108,
    ranger_hunter_mastery = 80005109,
    ranger_shadow_mastery = 80005110,
    ranger_snare_mastery = 80005111,
}

local function tags(...)
    return { ... }
end

---@type table<integer, RuntimeSkillEntry>
local SKILLS = {
    [SkillRuntimeConfig.Ids.rogue_basic_attack] = {
        id = SkillRuntimeConfig.Ids.rogue_basic_attack,
        symbol = "rogue_basic_attack",
        runtimeKind = "active",
        designKind = "active",
        classId = 1,
        name = "基础武器攻击",
        hidden = false,
        cooldown = 0,
        luaFile = "config.skill.skill_80001011",
        execution = { type = "basic_weapon_attack" },
        tags = tags("rogue", "basic_attack"),
        runtimeData = {
            skillType = 1,
        },
    },
    [SkillRuntimeConfig.Ids.rogue_execute_strike] = {
        id = SkillRuntimeConfig.Ids.rogue_execute_strike,
        symbol = "rogue_execute_strike",
        runtimeKind = "active",
        designKind = "active",
        classId = 1,
        name = "处决打击",
        hidden = false,
        cooldown = 2,
        luaFile = "config.skill.skill_80001013",
        execution = { type = "execute_strike" },
        tags = tags("rogue", "signature", "execute"),
        runtimeData = {
            skillType = 2,
            skillCost = 0,
        },
    },
    [SkillRuntimeConfig.Ids.rogue_trickster_blade] = {
        id = SkillRuntimeConfig.Ids.rogue_trickster_blade,
        symbol = "rogue_trickster_blade",
        runtimeKind = "active",
        designKind = "active",
        classId = 1,
        name = "扰乱飞刃",
        hidden = false,
        cooldown = 2,
        luaFile = "config.skill.skill_80001014",
        execution = { type = "trickster_blade" },
        tags = tags("rogue", "signature", "breach"),
        runtimeData = {
            skillType = 2,
            skillCost = 0,
            targetsSelections = {
                castTarget = E_CAST_TARGET.Enemy,
                ignoreFrontProtection = true,
                targetRow = 2,
            },
        },
    },
    [SkillRuntimeConfig.Ids.rogue_swashbuckler_thrust] = {
        id = SkillRuntimeConfig.Ids.rogue_swashbuckler_thrust,
        symbol = "rogue_swashbuckler_thrust",
        runtimeKind = "active",
        designKind = "active",
        classId = 1,
        name = "穿行突刺",
        hidden = false,
        cooldown = 2,
        luaFile = "config.skill.skill_80001015",
        execution = { type = "swashbuckler_thrust" },
        tags = tags("rogue", "signature", "sneak", "ignore_front"),
        runtimeData = {
            skillType = 2,
            skillCost = 0,
            targetsSelections = {
                castTarget = E_CAST_TARGET.Enemy,
                ignoreFrontProtection = true,
            },
        },
    },
    [SkillRuntimeConfig.Ids.rogue_sneak_attack] = {
        id = SkillRuntimeConfig.Ids.rogue_sneak_attack,
        symbol = "rogue_sneak_attack",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 1,
        name = "偷袭",
        hidden = true,
        cooldown = 0,
        trigger = "after_basic_attack_hit_each_turn",
        execution = { type = "sneak_attack" },
        tags = tags("rogue", "burst", "sneak"),
    },
    [SkillRuntimeConfig.Ids.rogue_shadow_step] = {
        id = SkillRuntimeConfig.Ids.rogue_shadow_step,
        symbol = "rogue_shadow_step",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 1,
        name = "影步切入",
        hidden = true,
        cooldown = 0,
        trigger = "first_basic_attack_ignore_front",
        execution = { type = "shadow_step" },
        tags = tags("rogue", "mobility"),
    },
    [SkillRuntimeConfig.Ids.rogue_flanking_expert] = {
        id = SkillRuntimeConfig.Ids.rogue_flanking_expert,
        symbol = "rogue_flanking_expert",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 1,
        name = "夹击老手",
        hidden = true,
        cooldown = 0,
        trigger = "sneak_attack_flank_bonus",
        execution = { type = "marker" },
        tags = tags("rogue", "sneak", "flank"),
    },
    [SkillRuntimeConfig.Ids.rogue_evasive_tumble] = {
        id = SkillRuntimeConfig.Ids.rogue_evasive_tumble,
        symbol = "rogue_evasive_tumble",
        runtimeKind = "passive",
        designKind = "reaction",
        classId = 1,
        name = "翻滚脱离",
        hidden = true,
        cooldown = 0,
        trigger = "first_melee_hit_reduction",
        execution = { type = "damage_reduction" },
        tags = tags("rogue", "survivability"),
    },
    [SkillRuntimeConfig.Ids.rogue_sneak_attack_mastery] = {
        id = SkillRuntimeConfig.Ids.rogue_sneak_attack_mastery,
        symbol = "rogue_sneak_attack_mastery",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 1,
        name = "偷袭专精",
        hidden = true,
        cooldown = 0,
        trigger = "sneak_attack_upgrade",
        execution = { type = "marker" },
        tags = tags("rogue", "mastery", "sneak"),
    },
    [SkillRuntimeConfig.Ids.rogue_subclass_mastery] = {
        id = SkillRuntimeConfig.Ids.rogue_subclass_mastery,
        symbol = "rogue_subclass_mastery",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 1,
        name = "子职专精",
        hidden = true,
        cooldown = 0,
        trigger = "subclass_bonus_damage",
        execution = { type = "marker" },
        tags = tags("rogue", "mastery", "subclass"),
    },
    [SkillRuntimeConfig.Ids.rogue_lightfoot_mastery] = {
        id = SkillRuntimeConfig.Ids.rogue_lightfoot_mastery,
        symbol = "rogue_lightfoot_mastery",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 1,
        name = "轻身专精",
        hidden = true,
        cooldown = 0,
        trigger = "first_melee_hit_extra_reduction",
        execution = { type = "marker" },
        tags = tags("rogue", "mastery", "survivability"),
    },
    [SkillRuntimeConfig.Ids.rogue_uncanny_dodge] = {
        id = SkillRuntimeConfig.Ids.rogue_uncanny_dodge,
        symbol = "rogue_uncanny_dodge",
        runtimeKind = "passive",
        designKind = "reaction",
        classId = 1,
        name = "Uncanny Dodge",
        hidden = true,
        cooldown = 0,
        trigger = "first_hit_damage_halved",
        execution = { type = "uncanny_dodge" },
        tags = tags("rogue", "survivability", "capstone"),
    },
    [SkillRuntimeConfig.Ids.rogue_executioner] = {
        id = SkillRuntimeConfig.Ids.rogue_executioner,
        symbol = "rogue_executioner",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 1,
        name = "处刑者",
        hidden = true,
        cooldown = 0,
        trigger = "executioner_bonus",
        execution = { type = "marker" },
        tags = tags("rogue", "capstone", "burst"),
    },
    [SkillRuntimeConfig.Ids.rogue_shadow_dancer] = {
        id = SkillRuntimeConfig.Ids.rogue_shadow_dancer,
        symbol = "rogue_shadow_dancer",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 1,
        name = "影舞者",
        hidden = true,
        cooldown = 0,
        trigger = "shadow_dancer_bonus",
        execution = { type = "marker" },
        tags = tags("rogue", "capstone", "tempo"),
    },
    [SkillRuntimeConfig.Ids.rogue_survivor] = {
        id = SkillRuntimeConfig.Ids.rogue_survivor,
        symbol = "rogue_survivor",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 1,
        name = "生还者",
        hidden = true,
        cooldown = 0,
        trigger = "survivor_counter_sneak",
        execution = { type = "marker" },
        tags = tags("rogue", "capstone", "survivability"),
    },
    [SkillRuntimeConfig.Ids.fighter_basic_attack] = {
        id = SkillRuntimeConfig.Ids.fighter_basic_attack,
        symbol = "fighter_basic_attack",
        runtimeKind = "active",
        designKind = "active",
        classId = 2,
        name = "基础武器攻击",
        hidden = false,
        cooldown = 0,
        luaFile = "config.skill.skill_80002001",
        execution = { type = "basic_weapon_attack" },
        tags = tags("fighter", "basic_attack"),
        runtimeData = {
            skillType = 1,
        },
    },
    [SkillRuntimeConfig.Ids.fighter_action_surge] = {
        id = SkillRuntimeConfig.Ids.fighter_action_surge,
        symbol = "fighter_action_surge",
        runtimeKind = "active",
        designKind = "active",
        classId = 2,
        name = "动作激增",
        hidden = false,
        cooldown = 3,
        luaFile = "config.skill.skill_80002003",
        execution = { type = "basic_attack_action", retarget = "random_enemy" },
        tags = tags("fighter", "signature", "burst"),
        runtimeData = {
            skillType = 2,
            skillCost = 0,
        },
    },
    [SkillRuntimeConfig.Ids.fighter_guard_stance] = {
        id = SkillRuntimeConfig.Ids.fighter_guard_stance,
        symbol = "fighter_guard_stance",
        runtimeKind = "active",
        designKind = "active",
        classId = 2,
        name = "护卫架势",
        hidden = false,
        cooldown = 3,
        luaFile = "config.skill.skill_80002005",
        execution = { type = "guard_stance" },
        tags = tags("fighter", "signature", "guard"),
        runtimeData = {
            skillType = 2,
            skillCost = 0,
        },
    },
    [SkillRuntimeConfig.Ids.fighter_second_wind] = {
        id = SkillRuntimeConfig.Ids.fighter_second_wind,
        symbol = "fighter_second_wind",
        runtimeKind = "passive",
        designKind = "passive",
        classId = 2,
        name = "二次生命",
        hidden = true,
        cooldown = 0,
        trigger = "hp_half_or_lower_once_per_battle",
        execution = { type = "second_wind" },
        tags = tags("fighter", "survivability"),
    },
    [SkillRuntimeConfig.Ids.fighter_precise_attack] = {
        id = SkillRuntimeConfig.Ids.fighter_precise_attack,
        symbol = "fighter_precise_attack",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 2,
        name = "精准攻击",
        hidden = true,
        cooldown = 0,
        trigger = "before_basic_attack_hit_check",
        execution = { type = "modify_basic_attack" },
        tags = tags("fighter", "basic_attack", "precision"),
    },
    [SkillRuntimeConfig.Ids.fighter_counter_basic] = {
        id = SkillRuntimeConfig.Ids.fighter_counter_basic,
        symbol = "fighter_counter_basic",
        runtimeKind = "passive",
        designKind = "reaction",
        classId = 2,
        name = "反击战法",
        hidden = true,
        cooldown = 0,
        trigger = "on_melee_targeted_each_turn",
        execution = { type = "counter_basic" },
        tags = tags("fighter", "reaction"),
    },
    [SkillRuntimeConfig.Ids.fighter_guard_counter] = {
        id = SkillRuntimeConfig.Ids.fighter_guard_counter,
        symbol = "fighter_guard_counter",
        runtimeKind = "passive",
        designKind = "reaction",
        classId = 2,
        name = "护卫反击",
        hidden = true,
        cooldown = 0,
        trigger = "on_ally_hit_while_guarding",
        execution = { type = "guard_counter" },
        tags = tags("fighter", "guard", "reaction"),
    },
    [SkillRuntimeConfig.Ids.fighter_second_wind_mastery] = {
        id = SkillRuntimeConfig.Ids.fighter_second_wind_mastery,
        symbol = "fighter_second_wind_mastery",
        runtimeKind = "passive",
        designKind = "passive",
        classId = 2,
        name = "续战专精",
        hidden = true,
        cooldown = 0,
        trigger = "second_wind_bonus_heal",
        execution = { type = "bonus_heal" },
        tags = tags("fighter", "survivability", "mastery"),
    },
    [SkillRuntimeConfig.Ids.fighter_extra_attack] = {
        id = SkillRuntimeConfig.Ids.fighter_extra_attack,
        symbol = "fighter_extra_attack",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 2,
        name = "额外攻击",
        hidden = true,
        cooldown = 0,
        trigger = "after_first_basic_attack_each_turn",
        execution = { type = "extra_attack" },
        tags = tags("fighter", "extra_attack"),
    },
    [SkillRuntimeConfig.Ids.fighter_sweeping_attack] = {
        id = SkillRuntimeConfig.Ids.fighter_sweeping_attack,
        symbol = "fighter_sweeping_attack",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 2,
        name = "横扫攻击",
        hidden = true,
        cooldown = 0,
        trigger = "after_basic_attack_hit",
        execution = { type = "sweeping_attack" },
        tags = tags("fighter", "basic_attack", "sweep"),
    },
    [SkillRuntimeConfig.Ids.monk_basic_attack] = {
        id = SkillRuntimeConfig.Ids.monk_basic_attack,
        symbol = "monk_basic_attack",
        runtimeKind = "active",
        designKind = "active",
        classId = 3,
        name = "徒手打击",
        hidden = false,
        cooldown = 0,
        luaFile = "config.skill.skill_80003011",
        execution = { type = "basic_weapon_attack" },
        tags = tags("monk", "basic_attack", "ignore_front"),
        runtimeData = {
            skillType = 1,
            targetsSelections = {
                castTarget = E_CAST_TARGET.Enemy,
                ignoreFrontProtection = true,
            },
        },
    },
    [SkillRuntimeConfig.Ids.monk_open_hand] = {
        id = SkillRuntimeConfig.Ids.monk_open_hand,
        symbol = "monk_open_hand",
        runtimeKind = "active",
        designKind = "active",
        classId = 3,
        name = "震劲掌",
        hidden = false,
        cooldown = 3,
        luaFile = "config.skill.skill_80003013",
        execution = { type = "open_hand_strike" },
        tags = tags("monk", "signature", "control", "ignore_front"),
        runtimeData = {
            skillType = 2,
            targetsSelections = {
                castTarget = E_CAST_TARGET.Enemy,
                ignoreFrontProtection = true,
            },
        },
    },
    [SkillRuntimeConfig.Ids.monk_shadow_combo] = {
        id = SkillRuntimeConfig.Ids.monk_shadow_combo,
        symbol = "monk_shadow_combo",
        runtimeKind = "active",
        designKind = "active",
        classId = 3,
        name = "影步连打",
        hidden = false,
        cooldown = 3,
        luaFile = "config.skill.skill_80003014",
        execution = { type = "shadow_combo" },
        tags = tags("monk", "signature", "mobility", "ignore_front"),
        runtimeData = {
            skillType = 2,
            targetsSelections = {
                castTarget = E_CAST_TARGET.Enemy,
                ignoreFrontProtection = true,
            },
        },
    },
    [SkillRuntimeConfig.Ids.monk_harmonize] = {
        id = SkillRuntimeConfig.Ids.monk_harmonize,
        symbol = "monk_harmonize",
        runtimeKind = "active",
        designKind = "active",
        classId = 3,
        name = "调息自愈",
        hidden = false,
        cooldown = 3,
        luaFile = "config.skill.skill_80003015",
        execution = { type = "harmonize" },
        tags = tags("monk", "signature", "recovery"),
        runtimeData = {
            skillType = 2,
            targetsSelections = {
                castTarget = E_CAST_TARGET.Alias,
                includeSelf = true,
            },
        },
    },
    [SkillRuntimeConfig.Ids.monk_martial_arts] = {
        id = SkillRuntimeConfig.Ids.monk_martial_arts,
        symbol = "monk_martial_arts",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 3,
        name = "武艺",
        hidden = true,
        cooldown = 0,
        trigger = "after_basic_attack_hit_each_turn",
        execution = { type = "martial_arts_followup" },
        tags = tags("monk", "basic_attack", "combo"),
    },
    [SkillRuntimeConfig.Ids.monk_flurry_training] = {
        id = SkillRuntimeConfig.Ids.monk_flurry_training,
        symbol = "monk_flurry_training",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 3,
        name = "连打技",
        hidden = true,
        cooldown = 0,
        trigger = "martial_arts_bonus_damage",
        execution = { type = "martial_arts_bonus" },
        tags = tags("monk", "combo"),
    },
    [SkillRuntimeConfig.Ids.monk_iron_mind] = {
        id = SkillRuntimeConfig.Ids.monk_iron_mind,
        symbol = "monk_iron_mind",
        runtimeKind = "passive",
        designKind = "passive",
        classId = 3,
        name = "守心技",
        hidden = true,
        cooldown = 0,
        trigger = "first_hit_damage_reduction",
        execution = { type = "self_damage_reduction" },
        tags = tags("monk", "defense"),
    },
    [SkillRuntimeConfig.Ids.monk_swift_step] = {
        id = SkillRuntimeConfig.Ids.monk_swift_step,
        symbol = "monk_swift_step",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 3,
        name = "疾风技",
        hidden = true,
        cooldown = 0,
        trigger = "ignore_front_protection",
        execution = { type = "ignore_front_protection" },
        tags = tags("monk", "mobility"),
    },
    [SkillRuntimeConfig.Ids.monk_body_mastery] = {
        id = SkillRuntimeConfig.Ids.monk_body_mastery,
        symbol = "monk_body_mastery",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 3,
        name = "体术专精",
        hidden = true,
        cooldown = 0,
        trigger = "basic_attack_bonus_damage",
        execution = { type = "basic_attack_bonus_damage" },
        tags = tags("monk", "basic_attack"),
    },
    [SkillRuntimeConfig.Ids.monk_combo_mastery] = {
        id = SkillRuntimeConfig.Ids.monk_combo_mastery,
        symbol = "monk_combo_mastery",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 3,
        name = "连击专精",
        hidden = true,
        cooldown = 0,
        trigger = "martial_arts_bonus_damage",
        execution = { type = "martial_arts_bonus_damage" },
        tags = tags("monk", "combo"),
    },
    [SkillRuntimeConfig.Ids.monk_body_guard] = {
        id = SkillRuntimeConfig.Ids.monk_body_guard,
        symbol = "monk_body_guard",
        runtimeKind = "passive",
        designKind = "passive",
        classId = 3,
        name = "护体专精",
        hidden = true,
        cooldown = 0,
        trigger = "first_hit_damage_reduction",
        execution = { type = "self_damage_reduction" },
        tags = tags("monk", "defense"),
    },
    [SkillRuntimeConfig.Ids.monk_extra_attack] = {
        id = SkillRuntimeConfig.Ids.monk_extra_attack,
        symbol = "monk_extra_attack",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 3,
        name = "额外攻击",
        hidden = true,
        cooldown = 0,
        trigger = "on_normal_attack_finish",
        execution = { type = "extra_attack" },
        tags = tags("monk", "extra_attack"),
    },
    [SkillRuntimeConfig.Ids.monk_disruption_mastery] = {
        id = SkillRuntimeConfig.Ids.monk_disruption_mastery,
        symbol = "monk_disruption_mastery",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 3,
        name = "截脉宗师",
        hidden = true,
        cooldown = 0,
        trigger = "extra_attack_control",
        execution = { type = "open_hand_mastery" },
        tags = tags("monk", "control", "mastery"),
    },
    [SkillRuntimeConfig.Ids.monk_purity_mastery] = {
        id = SkillRuntimeConfig.Ids.monk_purity_mastery,
        symbol = "monk_purity_mastery",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 3,
        name = "无垢宗师",
        hidden = true,
        cooldown = 0,
        trigger = "martial_arts_heal",
        execution = { type = "purity_mastery" },
        tags = tags("monk", "recovery", "mastery"),
    },
    [SkillRuntimeConfig.Ids.paladin_basic_attack] = {
        id = SkillRuntimeConfig.Ids.paladin_basic_attack,
        symbol = "paladin_basic_attack",
        runtimeKind = "active",
        designKind = "active",
        classId = 4,
        name = "圣武打击",
        hidden = false,
        cooldown = 0,
        luaFile = "config.skill.skill_80004011",
        execution = { type = "basic_weapon_attack" },
        tags = tags("paladin", "basic_attack"),
        runtimeData = {
            skillType = 1,
        },
    },
    [SkillRuntimeConfig.Ids.paladin_lay_on_hands] = {
        id = SkillRuntimeConfig.Ids.paladin_lay_on_hands,
        symbol = "paladin_lay_on_hands",
        runtimeKind = "active",
        designKind = "active",
        classId = 4,
        name = "圣疗之手",
        hidden = false,
        cooldown = 3,
        luaFile = "config.skill.skill_80004013",
        execution = { type = "lay_on_hands" },
        tags = tags("paladin", "signature", "heal"),
        runtimeData = {
            skillType = 2,
        },
    },
    [SkillRuntimeConfig.Ids.paladin_vengeance_smite] = {
        id = SkillRuntimeConfig.Ids.paladin_vengeance_smite,
        symbol = "paladin_vengeance_smite",
        runtimeKind = "active",
        designKind = "active",
        classId = 4,
        name = "复仇裁击",
        hidden = false,
        cooldown = 3,
        luaFile = "config.skill.skill_80004014",
        execution = { type = "vengeance_smite" },
        tags = tags("paladin", "signature", "burst"),
        runtimeData = {
            skillType = 2,
        },
    },
    [SkillRuntimeConfig.Ids.paladin_guardian_aura] = {
        id = SkillRuntimeConfig.Ids.paladin_guardian_aura,
        symbol = "paladin_guardian_aura",
        runtimeKind = "active",
        designKind = "active",
        classId = 4,
        name = "守护灵光",
        hidden = false,
        cooldown = 3,
        luaFile = "config.skill.skill_80004015",
        execution = { type = "guardian_aura" },
        tags = tags("paladin", "signature", "aura"),
        runtimeData = {
            skillType = 2,
            targetsSelections = {
                castTarget = E_CAST_TARGET.Alias,
                includeSelf = true,
            },
        },
    },
    [SkillRuntimeConfig.Ids.paladin_divine_smite] = {
        id = SkillRuntimeConfig.Ids.paladin_divine_smite,
        symbol = "paladin_divine_smite",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 4,
        name = "神圣惩击",
        hidden = true,
        cooldown = 0,
        trigger = "after_first_basic_attack_hit_each_turn",
        execution = { type = "divine_smite" },
        tags = tags("paladin", "basic_attack", "radiant"),
    },
    [SkillRuntimeConfig.Ids.paladin_shelter_prayer] = {
        id = SkillRuntimeConfig.Ids.paladin_shelter_prayer,
        symbol = "paladin_shelter_prayer",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 4,
        name = "庇护祷法",
        hidden = true,
        cooldown = 0,
        trigger = "ally_first_hit_reduction",
        execution = { type = "shelter_prayer" },
        tags = tags("paladin", "defense", "support"),
    },
    [SkillRuntimeConfig.Ids.paladin_heavy_armor_prayer] = {
        id = SkillRuntimeConfig.Ids.paladin_heavy_armor_prayer,
        symbol = "paladin_heavy_armor_prayer",
        runtimeKind = "passive",
        designKind = "passive",
        classId = 4,
        name = "重甲祷法",
        hidden = true,
        cooldown = 0,
        trigger = "self_first_hit_reduction",
        execution = { type = "heavy_armor_prayer" },
        tags = tags("paladin", "defense"),
    },
    [SkillRuntimeConfig.Ids.paladin_judgement_prayer] = {
        id = SkillRuntimeConfig.Ids.paladin_judgement_prayer,
        symbol = "paladin_judgement_prayer",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 4,
        name = "裁决祷法",
        hidden = true,
        cooldown = 0,
        trigger = "first_basic_attack_ignore_ac",
        execution = { type = "judgement_prayer" },
        tags = tags("paladin", "precision"),
    },
    [SkillRuntimeConfig.Ids.paladin_smite_mastery] = {
        id = SkillRuntimeConfig.Ids.paladin_smite_mastery,
        symbol = "paladin_smite_mastery",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 4,
        name = "惩击专精",
        hidden = true,
        cooldown = 0,
        trigger = "divine_smite_bonus",
        execution = { type = "smite_mastery" },
        tags = tags("paladin", "radiant"),
    },
    [SkillRuntimeConfig.Ids.paladin_healing_mastery] = {
        id = SkillRuntimeConfig.Ids.paladin_healing_mastery,
        symbol = "paladin_healing_mastery",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 4,
        name = "圣疗专精",
        hidden = true,
        cooldown = 0,
        trigger = "lay_on_hands_bonus",
        execution = { type = "healing_mastery" },
        tags = tags("paladin", "heal"),
    },
    [SkillRuntimeConfig.Ids.paladin_aura_mastery] = {
        id = SkillRuntimeConfig.Ids.paladin_aura_mastery,
        symbol = "paladin_aura_mastery",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 4,
        name = "灵光专精",
        hidden = true,
        cooldown = 0,
        trigger = "guardian_aura_bonus",
        execution = { type = "aura_mastery" },
        tags = tags("paladin", "aura"),
    },
    [SkillRuntimeConfig.Ids.paladin_extra_attack] = {
        id = SkillRuntimeConfig.Ids.paladin_extra_attack,
        symbol = "paladin_extra_attack",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 4,
        name = "额外攻击",
        hidden = true,
        cooldown = 0,
        trigger = "on_normal_attack_finish",
        execution = { type = "extra_attack" },
        tags = tags("paladin", "extra_attack"),
    },
    [SkillRuntimeConfig.Ids.paladin_execution_knight] = {
        id = SkillRuntimeConfig.Ids.paladin_execution_knight,
        symbol = "paladin_execution_knight",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 4,
        name = "裁决圣骑",
        hidden = true,
        cooldown = 0,
        trigger = "extra_attack_bonus_damage",
        execution = { type = "execution_knight" },
        tags = tags("paladin", "radiant", "mastery"),
    },
    [SkillRuntimeConfig.Ids.paladin_merciful_knight] = {
        id = SkillRuntimeConfig.Ids.paladin_merciful_knight,
        symbol = "paladin_merciful_knight",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 4,
        name = "慈光圣骑",
        hidden = true,
        cooldown = 0,
        trigger = "attack_heal_ally",
        execution = { type = "merciful_knight" },
        tags = tags("paladin", "heal", "mastery"),
    },
    [SkillRuntimeConfig.Ids.paladin_sanctuary_knight] = {
        id = SkillRuntimeConfig.Ids.paladin_sanctuary_knight,
        symbol = "paladin_sanctuary_knight",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 4,
        name = "圣域圣骑",
        hidden = true,
        cooldown = 0,
        trigger = "attack_enable_sanctuary",
        execution = { type = "sanctuary_knight" },
        tags = tags("paladin", "aura", "mastery"),
    },
    [SkillRuntimeConfig.Ids.ranger_basic_attack] = {
        id = SkillRuntimeConfig.Ids.ranger_basic_attack,
        symbol = "ranger_basic_attack",
        runtimeKind = "active",
        designKind = "active",
        classId = 5,
        name = "远程基础攻击",
        hidden = false,
        cooldown = 0,
        luaFile = "config.skill.skill_80005011",
        execution = { type = "basic_weapon_attack" },
        tags = tags("ranger", "basic_attack", "ranged"),
        runtimeData = {
            skillType = 1,
            targetsSelections = {
                castTarget = E_CAST_TARGET.Enemy,
                ignoreFrontProtection = true,
            },
        },
    },
    [SkillRuntimeConfig.Ids.ranger_hunter_shot] = {
        id = SkillRuntimeConfig.Ids.ranger_hunter_shot,
        symbol = "ranger_hunter_shot",
        runtimeKind = "active",
        designKind = "active",
        classId = 5,
        name = "猎杀箭",
        hidden = false,
        cooldown = 3,
        luaFile = "config.skill.skill_80005013",
        execution = { type = "hunter_shot" },
        tags = tags("ranger", "signature", "mark"),
        runtimeData = {
            skillType = 2,
            targetsSelections = {
                castTarget = E_CAST_TARGET.Enemy,
                ignoreFrontProtection = true,
            },
        },
    },
    [SkillRuntimeConfig.Ids.ranger_shadow_shot] = {
        id = SkillRuntimeConfig.Ids.ranger_shadow_shot,
        symbol = "ranger_shadow_shot",
        runtimeKind = "active",
        designKind = "active",
        classId = 5,
        name = "暮影射击",
        hidden = false,
        cooldown = 3,
        luaFile = "config.skill.skill_80005014",
        execution = { type = "shadow_shot" },
        tags = tags("ranger", "signature", "backline"),
        runtimeData = {
            skillType = 2,
            targetsSelections = {
                castTarget = E_CAST_TARGET.Enemy,
                ignoreFrontProtection = true,
            },
        },
    },
    [SkillRuntimeConfig.Ids.ranger_snare_shot] = {
        id = SkillRuntimeConfig.Ids.ranger_snare_shot,
        symbol = "ranger_snare_shot",
        runtimeKind = "active",
        designKind = "active",
        classId = 5,
        name = "缠绕箭",
        hidden = false,
        cooldown = 3,
        luaFile = "config.skill.skill_80005015",
        execution = { type = "snare_shot" },
        tags = tags("ranger", "signature", "control"),
        runtimeData = {
            skillType = 2,
            targetsSelections = {
                castTarget = E_CAST_TARGET.Enemy,
                ignoreFrontProtection = true,
            },
        },
    },
    [SkillRuntimeConfig.Ids.ranger_hunter_mark] = {
        id = SkillRuntimeConfig.Ids.ranger_hunter_mark,
        symbol = "ranger_hunter_mark",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 5,
        name = "猎人印记",
        hidden = true,
        cooldown = 0,
        trigger = "mark_on_hit",
        execution = { type = "hunter_mark" },
        tags = tags("ranger", "mark"),
    },
    [SkillRuntimeConfig.Ids.ranger_tracking_skill] = {
        id = SkillRuntimeConfig.Ids.ranger_tracking_skill,
        symbol = "ranger_tracking_skill",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 5,
        name = "追猎技巧",
        hidden = true,
        cooldown = 0,
        trigger = "mark_bonus_damage",
        execution = { type = "tracking_skill" },
        tags = tags("ranger", "mark", "damage"),
    },
    [SkillRuntimeConfig.Ids.ranger_precise_shot] = {
        id = SkillRuntimeConfig.Ids.ranger_precise_shot,
        symbol = "ranger_precise_shot",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 5,
        name = "精准射击",
        hidden = true,
        cooldown = 0,
        trigger = "mark_hit_bonus",
        execution = { type = "precise_shot" },
        tags = tags("ranger", "mark", "precision"),
    },
    [SkillRuntimeConfig.Ids.ranger_wild_endurance] = {
        id = SkillRuntimeConfig.Ids.ranger_wild_endurance,
        symbol = "ranger_wild_endurance",
        runtimeKind = "passive",
        designKind = "passive",
        classId = 5,
        name = "野外坚忍",
        hidden = true,
        cooldown = 0,
        trigger = "self_first_hit_reduction",
        execution = { type = "wild_endurance" },
        tags = tags("ranger", "defense"),
    },
    [SkillRuntimeConfig.Ids.ranger_mark_mastery] = {
        id = SkillRuntimeConfig.Ids.ranger_mark_mastery,
        symbol = "ranger_mark_mastery",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 5,
        name = "印记专精",
        hidden = true,
        cooldown = 0,
        trigger = "mark_bonus_damage",
        execution = { type = "mark_mastery" },
        tags = tags("ranger", "mark"),
    },
    [SkillRuntimeConfig.Ids.ranger_subclass_mastery] = {
        id = SkillRuntimeConfig.Ids.ranger_subclass_mastery,
        symbol = "ranger_subclass_mastery",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 5,
        name = "子职专精",
        hidden = true,
        cooldown = 0,
        trigger = "subclass_skill_bonus_damage",
        execution = { type = "subclass_mastery" },
        tags = tags("ranger", "signature"),
    },
    [SkillRuntimeConfig.Ids.ranger_survival_mastery] = {
        id = SkillRuntimeConfig.Ids.ranger_survival_mastery,
        symbol = "ranger_survival_mastery",
        runtimeKind = "passive",
        designKind = "passive",
        classId = 5,
        name = "生存专精",
        hidden = true,
        cooldown = 0,
        trigger = "self_first_hit_reduction",
        execution = { type = "survival_mastery" },
        tags = tags("ranger", "defense"),
    },
    [SkillRuntimeConfig.Ids.ranger_extra_attack] = {
        id = SkillRuntimeConfig.Ids.ranger_extra_attack,
        symbol = "ranger_extra_attack",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 5,
        name = "额外攻击",
        hidden = true,
        cooldown = 0,
        trigger = "on_normal_attack_finish",
        execution = { type = "extra_attack" },
        tags = tags("ranger", "extra_attack"),
    },
    [SkillRuntimeConfig.Ids.ranger_hunter_mastery] = {
        id = SkillRuntimeConfig.Ids.ranger_hunter_mastery,
        symbol = "ranger_hunter_mastery",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 5,
        name = "逐猎宗师",
        hidden = true,
        cooldown = 0,
        trigger = "first_hit_bonus_damage",
        execution = { type = "hunter_mastery" },
        tags = tags("ranger", "mark", "mastery"),
    },
    [SkillRuntimeConfig.Ids.ranger_shadow_mastery] = {
        id = SkillRuntimeConfig.Ids.ranger_shadow_mastery,
        symbol = "ranger_shadow_mastery",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 5,
        name = "影袭宗师",
        hidden = true,
        cooldown = 0,
        trigger = "extra_attack_bonus_damage",
        execution = { type = "shadow_mastery" },
        tags = tags("ranger", "backline", "mastery"),
    },
    [SkillRuntimeConfig.Ids.ranger_snare_mastery] = {
        id = SkillRuntimeConfig.Ids.ranger_snare_mastery,
        symbol = "ranger_snare_mastery",
        runtimeKind = "passive",
        designKind = "feature",
        classId = 5,
        name = "缚林宗师",
        hidden = true,
        cooldown = 0,
        trigger = "marked_target_control",
        execution = { type = "snare_mastery" },
        tags = tags("ranger", "control", "mastery"),
    },
}

local function deepCopy(value)
    if type(value) ~= "table" then
        return value
    end
    local result = {}
    for k, v in pairs(value) do
        result[k] = deepCopy(v)
    end
    return result
end

---@param skillId integer
---@return RuntimeSkillEntry|nil
function SkillRuntimeConfig.Get(skillId)
    local entry = SKILLS[tonumber(skillId) or 0]
    if not entry then
        return nil
    end
    return deepCopy(entry)
end

---@param classId integer
---@return RuntimeSkillEntry[]
function SkillRuntimeConfig.GetByClass(classId)
    local result = {}
    for _, entry in pairs(SKILLS) do
        if tonumber(entry.classId) == tonumber(classId) then
            result[#result + 1] = deepCopy(entry)
        end
    end
    table.sort(result, function(a, b)
        return (tonumber(a.id) or 0) < (tonumber(b.id) or 0)
    end)
    return result
end

---@param skillId integer
---@return boolean
function SkillRuntimeConfig.IsBasicAttackSkill(skillId)
    local entry = SKILLS[tonumber(skillId) or 0]
    if not entry then
        return false
    end
    for _, tag in ipairs(entry.tags or {}) do
        if tag == "basic_attack" then
            return true
        end
    end
    return false
end

return SkillRuntimeConfig
